### ISSUE TITLE
API to interact with ordinal data

### ISSUE THREAD

**Issue by whoabuddy** [bitcoin-nfts/ordinals#6]
Option 1: run a full bitcoin node, create an index with ord, and use the ord explorer

Option 2: https://ordapi.xyz/

any others?

Also found these services:

- [Ordinal Hub](https://www.ordinalhub.com/)
- [Ordinals Directory](https://ordinalsdirectory.com/)

**Comment by diwakergupta** [comment]
@whoabuddy Hiro is building an Ordinals API too, would love to understand your requirements.

**Comment by whoabuddy** [comment]
No direct requirements at this time - compiling resources at this point and hoping to learn more of what's out there and from what other projects have done.

**Comment by whoabuddy** [comment]
Closing this out as the Hiro API works great for our use cases! :clap:
